
package uy.com.antel;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NamingException", targetNamespace = "http://antel.com.uy/")
public class NamingException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NamingException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NamingException_Exception(String message, NamingException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NamingException_Exception(String message, NamingException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: uy.com.antel.NamingException
     */
    public NamingException getFaultInfo() {
        return faultInfo;
    }

}
