package uy.com.antel;

public enum TipoRespuesta {

    VENTA_EXITOSA,
    ANULACION_EXITOSA,
    ERROR_ANULACION_FECHA,
    ERROR_ANULACION_NO_EXISTE,
    ERROR_ANULACION_YA_ANULADO,
    ERROR_ANULACION_GRAL,
    ERROR_AUTENTICACION_TERMINAL

}
