
package uy.com.antel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ImmWsImpService", targetNamespace = "http://antel.com.uy/", wsdlLocation = "http://localhost:8080/servlet/sv?wsdl")
public class ImmWsImpService
    extends Service
{

    private final static URL IMMWSIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMMWSIMPSERVICE_EXCEPTION;
    private final static QName IMMWSIMPSERVICE_QNAME = new QName("http://antel.com.uy/", "ImmWsImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servlet/sv?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMMWSIMPSERVICE_WSDL_LOCATION = url;
        IMMWSIMPSERVICE_EXCEPTION = e;
    }

    public ImmWsImpService() {
        super(__getWsdlLocation(), IMMWSIMPSERVICE_QNAME);
    }

    public ImmWsImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMMWSIMPSERVICE_QNAME, features);
    }

    public ImmWsImpService(URL wsdlLocation) {
        super(wsdlLocation, IMMWSIMPSERVICE_QNAME);
    }

    public ImmWsImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMMWSIMPSERVICE_QNAME, features);
    }

    public ImmWsImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImmWsImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImmWsImp
     */
    @WebEndpoint(name = "ImmWsImpPort")
    public ImmWsImp getImmWsImpPort() {
        return super.getPort(new QName("http://antel.com.uy/", "ImmWsImpPort"), ImmWsImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImmWsImp
     */
    @WebEndpoint(name = "ImmWsImpPort")
    public ImmWsImp getImmWsImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://antel.com.uy/", "ImmWsImpPort"), ImmWsImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMMWSIMPSERVICE_EXCEPTION!= null) {
            throw IMMWSIMPSERVICE_EXCEPTION;
        }
        return IMMWSIMPSERVICE_WSDL_LOCATION;
    }

}
